

export const USER_ACTION_TYPES={
    SET_CURRENT_USER:'user/SET_CURRENT_USER',
    SET_IS_CHECK_LOGIN_UNDER_PROGRESS:'user/SET_IS_CHECK_LOGIN_UNDER_PROGRESS',
    CHECK_USER_SESSION:'user/CHECK_USER_SESSION',
    EMAIL_SIGN_IN_START:'user/EMAIL_SIGN_IN_START',
    GOOGLE_SIGN_IN_START:'user/GOOGLE_SIGN_IN_START',
    SIGN_IN_SUCCESS:'user/SIGN_IN_SUCCESS',
    SIGN_IN_FAILED:'user/SIGN_IN_FAILED',
    SET_USERNAME:'user/SET_USERNAME'

};