
export const CART_ACTION_TYPE={
    // SET_CART_ITEMS:'cart/SET_CART_ITEMS',
    SET_IS_CART_OPEN:'cart/SET_IS_CART_OPEN',
    SET_CART_COUNT:'cart/SET_CART_COUNT',
    SET_CART_TOTAL:'cart/SET_CART_TOTAL',
    ADD_ITEM_TO_CART:'cart/ADD_ITEM_TO_CART',
    REMOVE_ITEM_FROM_CART:'cart/REMOVE_ITEM_FROM_CART',
    UPDATE_ITEM_QUANTITY_IN_CART:'cart/UPDATE_ITEM_QUANTITY_IN_CART',
    CLEAR_CART_ITEMS:'cart/CLEAR_CART_ITEMS',

}
